version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: study-user
      MONGO_INITDB_ROOT_PASSWORD: study-pw
      MONGO_INITDB_DATABASE: study
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d